
### 1. Login as sys admin
POST localhost:8080/api/login/v1/email
Content-Type: application/json

{
    "email":"defaultSysAdmin@gmail.com",
    "password":"JustAPasswordForDefaultSysAdmin"
}

### 2. Create database for tenant
POST localhost:8080/api/tenants/v1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjcwODQ3MTA4LCJ1c2VySWQiOjEsInJvbGVzIjpbIlNZU19BRE1JTiJdLCJlbWFpbCI6ImRlZmF1bHRTeXNBZG1pbkBnbWFpbC5jb20ifQ.y9ezwf6zeZdyWgDn2xr8QspzqDKKOKYh7ZBWF_8yuv6ze76m0jQVFq_GGQK7VcreQKPj7RM8-ShUWRqeyfj2Hg

{
  "name": "test_tenant",
  "dbName": "test_tenant",
  "userName": "test_tenant_userName",
  "dbPassword": "test_tenant_password",
  "user": {
    "email": "test123@gmail.com",
    "password": "test_tenant_password"
  }
}

### 3. Create a user with "ADMIN" role for this tenant

POST localhost:8080/api/users/v1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjcwNzgyMTk1LCJ1c2VySWQiOjEsInJvbGVzIjpbIlNZU19BRE1JTiJdLCJlbWFpbCI6ImRlZmF1bHRTeXNBZG1pbkBnbWFpbC5jb20ifQ.U9okKzws0pEqdUMfJ5KBHfwp7ki_Kg-_-KpEM5B94CKGG3jI2JLup_igUMKweudoUZ3ISgZ_x2rxczzcq-ho1A

{
  "tenantId": 2,
  "email": "admin@gmail.com",
  "password": "admin_password",
  "roles" : ["ADMIN"]
}

### 4. Login as ADMIN of this tenant

POST localhost:8080/api/login/v1/email
Content-Type: application/json

{
  "email":"admin@gmail.com",
  "password":"admin_password"
}

### 5. Create a research in this tenant

POST localhost:8080/api/researches/v1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiZXhwIjoxNjcwNzgyMzI1LCJ1c2VySWQiOjMsInRlbmFudElkIjoyLCJyb2xlcyI6WyJBRE1JTiJdLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9.V5uXEomX3TY5LqtL4DRyXKYmD3FNCFzvKWTpZfZIz7L4p0hxnzEn36XD7MXI2tE9RMZuEUsaELRswy9FRri16A

{
  "name": "Just a test research name",
  "description": "Just a test research description"
}


### 6. Get list of all available researches

GET localhost:8080/api/researches/v1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIzIiwiZXhwIjoxNjcwNzgyMzI1LCJ1c2VySWQiOjMsInRlbmFudElkIjoyLCJyb2xlcyI6WyJBRE1JTiJdLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSJ9.V5uXEomX3TY5LqtL4DRyXKYmD3FNCFzvKWTpZfZIz7L4p0hxnzEn36XD7MXI2tE9RMZuEUsaELRswy9FRri16A